language: node_js
node_js: node
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.99.68.224
install:
- npm install npm -g
- npm install --registry=https://registry.npm.taobao.org
script:
- npm run build:dev
after_success:
- ssh root@47.99.68.224
# - git init
# - git config user.name "鹿丶羽"
# - git config user.email "panyupy@vip.qq.com"
# - git add .
# - git commit -m "Update docs"
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# - rsync -az --delete ./dist/* travis@gz.oidiotlin.com:/var/www/mdzz-web/