language: node_js
node_js: node
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.99.68.224
before_install:
- openssl aes-256-cbc -K $encrypted_aed4f01d17aa_key -iv $encrypted_aed4f01d17aa_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- npm install npm -g
- npm install
script:
- npm run build:prod
after_success:
- chmod 600 deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add deploy_rsa
- ssh root@47.99.68.224 'rm -rf /home/www/htdocs/*'
- scp -r-v dist/* root@47.99.68.224:/home/www/htdocs
