language: node_js
node_js: node
branches:
  only:
  - master
# addons:
#   ssh_known_hosts:
#   - gz.oidiotlin.com
install:
- npm install --registry=https://registry.npm.taobao.org
- npm install npm -g
script:
- npm run build
# after_success:
# - rsync -az --delete ./dist/* travis@gz.oidiotlin.com:/var/www/mdzz-web/